name: sms_circus

x-common:
  &x-common
  networks:
    - sms_circus

services:
  rabbit:
    <<: *x-common
    container_name: rabbit
    build: ./docker/rabbit
    hostname: rabbit_host
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  monitoring:
    <<: *x-common
    container_name: monitoring
    build: .
    command: streamlit run /app/monitor.py --server.port 8501
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      rabbit:
        condition: service_healthy
      postgres:
        condition: service_healthy

  postgres:
    <<: *x-common
    container_name: postgres
    hostname: postgres
    image: postgres:16
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d sms -U sms"]
      interval: 10s
      timeout: 5s
      retries: 5

  controller:
    <<: *x-common
    build: .
    container_name: controller
    env_file:
      - .env
    depends_on:
      rabbit:
        condition: service_healthy
      postgres:
        condition: service_healthy
    command: "tail -f /dev/null"


networks:
  sms_circus:
